#!/usr/bin/env python3
"""
apply_branding.py — stamp MagicBridgeV2 branding across the box.

Reads branding/branding.env and applies it to:
  1. the MagicBridgeV2 web UI (title, theme colours, logo/favicon paths),
  2. the kvmd-oled splash config (front-panel text),
  3. a generated CSS theme file the UI imports.

Designed to be safe when run without hardware / before kvmd paths exist:
every target is optional and skipped (with a note) if absent, so the same
script runs in dev and on-device. Idempotent.
"""
from __future__ import annotations
import argparse, os, re, sys, shutil
from pathlib import Path

def load_env(path: Path) -> dict:
    env = {}
    if not path.exists():
        sys.exit(f"branding.env not found at {path}")
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip().strip('"').strip("'")
    return env

def write_theme_css(env: dict, web_dir: Path):
    web_dir.mkdir(parents=True, exist_ok=True)
    css = f""":root {{
  --mb-bg: {env.get('MB_COLOR_BG', '#07131a')};
  --mb-accent: {env.get('MB_COLOR_ACCENT', '#00e5ff')};
  --mb-accent-2: {env.get('MB_COLOR_ACCENT2', '#b026ff')};
  --mb-text: {env.get('MB_COLOR_TEXT', '#e8f6fb')};
  --mb-title: "{env.get('MB_UI_TITLE', 'MagicBridgeV2')}";
}}
/* Generated by apply_branding.py — do not edit by hand. */
"""
    (web_dir / "theme.generated.css").write_text(css)
    print(f"  ✓ wrote {web_dir/'theme.generated.css'}")

def patch_ui_title(env: dict, web_dir: Path):
    index = web_dir / "index.html"
    if not index.exists():
        print("  · web/index.html not present yet — skipping title patch")
        return
    html = index.read_text()
    title = env.get("MB_UI_TITLE", "MagicBridgeV2")
    html = re.sub(r"<title>.*?</title>", f"<title>{title}</title>", html, flags=re.S)
    index.write_text(html)
    print(f"  ✓ set UI <title> to {title}")

def patch_oled(env: dict):
    """Point kvmd-oled at MagicBridge splash text via override.d (no core edits)."""
    oled_override = Path("/etc/kvmd/override.d/50-magicbridge-oled.yaml")
    if not oled_override.parent.exists():
        print("  · /etc/kvmd/override.d not present (no kvmd here) — skipping OLED")
        return
    l1 = env.get("MB_OLED_LINE1", "MagicBridgeV2")
    l2 = env.get("MB_OLED_LINE2", "starting...")
    oled_override.write_text(
        "kvmd:\n"
        "    oled:\n"
        f"        # MagicBridgeV2 splash\n"
        f"        text: |\n            {l1}\n            {l2}\n"
    )
    print(f"  ✓ OLED splash → '{l1}' / '{l2}'")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="/opt/magicbridge",
                    help="MagicBridgeV2 install root")
    args = ap.parse_args()
    root = Path(args.root)
    env = load_env(root / "branding" / "branding.env")
    print(f"Applying branding: {env.get('MB_PRODUCT_NAME','MagicBridgeV2')}")
    write_theme_css(env, root / "web")
    patch_ui_title(env, root / "web")
    patch_oled(env)
    print("Branding applied.")

if __name__ == "__main__":
    main()
